export const defaultSettings = {
  locale: "en",
  resolution: 720,
  xhome_bitrate_mode: "auto",
  xhome_bitrate: 20,
  xcloud_bitrate_mode: "auto",
  xcloud_bitrate: 20,
  preferred_game_language: "en-US",
  force_region_ip: "",
  codec: "",
  vibration: true,
  vibration_mode: "Native",
  gamepad_kernal: "Native",
  dead_zone: 0.1,
  video_format: "",
  virtual_gamepad_opacity: 0.6,
  gamepad_maping: null,
  native_gamepad_maping: null,
  ipv6: false,
  display_options: {
    sharpness: 5,
    saturation: 100,
    contrast: 100,
    brightness: 100,
  },
  debug: false,
};
